export default {
  Black: 'Poppins-Black',
  Bold: 'Poppins-Bold',
  BoldItalic: 'Poppins-BoldItalic',
  Bold: 'Poppins-ExtraBold',
  ExtraLight: 'Poppins-ExtraLight',
  ExtraLightItalic: 'Poppins-ExtraLightItalic',
  Italic: 'Poppins-Italic',
  Light: 'Poppins-Light',
  LightItalic: 'Poppins-LightItalic',
  Medium: 'Poppins-Medium',
  MediumItalic: 'Poppins-MediumItalic',
  Regular: 'Poppins-Regular',
  SemiBoldItalic: 'Poppins-SemiBoldItalic',
  SemiBold: 'Poppins-SemiBold',
  Thin: 'Poppins-Thin',
  ThinItalic: 'Poppins-ThinItalic',
};
